fail_fast: false
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-tabs
        exclude: "vendor-prefixes\\.txt$|.git/COMMIT_EDITMSG"
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]
        exclude: |
          (?x)^(
            app/include/drivers/behavior\.h|
            app/src/behaviors/behavior_caps_word\.c|
            app/src/behaviors/behavior_tap_dance\.c|
            app/src/keymap\.c|
            app/src/kscan_sideband_behaviors\.c|
            app/src/pointing/input_listener\.c|
            app/src/sensors\.c|
            app/tests/trackpad-input/basic/src/main\.c|
            app/tests/trackpad-input/scroll-gestures/src/main\.c
          )$
        args:
          - --dry-run
          - --Werror
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 787fb9f542b140ba0b2aced38e6a3e68021647a3
    hooks:
      - id: prettier
        exclude: |
          (?x)^(
              .git/COMMIT_EDITMSG|
              CHANGELOG.md|
              .release-please-manifest.json
          )$
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [--show-diff-on-failure]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
        exclude: "\\.mustache$"
