name: format-once
on:
  workflow_dispatch:

permissions:
  contents: write  # needed to push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # use GITHUB_TOKEN for push

      - name: Set bot identity
        run: |
          git config user.name  "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install "pre-commit==4.3.0"

      - name: Run clang-format via pre-commit on targeted files
        run: |
          # Install pre-commit hooks to get the formatting tools
          pre-commit install --install-hooks
          # Run clang-format on specific files (will auto-fix)
          pre-commit run clang-format --files \
            app/tests/drivers_test/src/main.c \
            app/tests/drivers_test/src/test_minimal.c || true

      - name: Commit and push if changes
        run: |
          if ! git diff --quiet; then
            git add -A
            git commit -m "style: auto-format via pre-commit (clang-format v18.1.8)"
            git push
          else
            echo "No formatting changes."
          fi