name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Expert diagnostic step to see exactly what's failing
      - name: Show clang-format version and dump effective style
        run: |
          clang-format --version || true
          # Dumping config ensures the tool finds .clang-format at repo root
          clang-format --style=file --dump-config > /tmp/clang-style.txt || true
          sed -n '1,60p' /tmp/clang-style.txt || true

      # Force verbose pre-commit output before the action wrapper
      - name: Pre-commit (diagnostic run)
        run: |
          python -m pip install --upgrade pip
          pip install "pre-commit==4.3.0"
          pre-commit --version
          # Verbose, show diffs, all hooks, all files
          pre-commit run --all-files --verbose --show-diff-on-failure || true

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
