name: Tests

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "app/run-test.sh"
      - "app/tests/**"
      - "app/src/**"
      - "app/include/**"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "app/run-test.sh"
      - "app/tests/**"
      - "app/src/**"
      - "app/include/**"

jobs:
  collect-tests:
    outputs:
      test-dirs: ${{ steps.test-dirs.outputs.test-dirs }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find test directories
        id: test-dirs
        run: |
          cd app/tests/
          export TESTS=$(find . -mindepth 1 -maxdepth 1 -type d -not -name "ble*" | cut -c3- | jq -R -s -c 'split("\n")[:-1]')
          echo "test-dirs=${TESTS}" >> $GITHUB_OUTPUT
  run-tests:
    needs: collect-tests
    strategy:
      matrix:
        test: ${{ fromJSON(needs.collect-tests.outputs.test-dirs) }}
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.5
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: Initialize workspace (idempotent)
        run: |
          set -euxo pipefail
          cd "$GITHUB_WORKSPACE"
          if ! west topdir >/dev/null 2>&1; then
            west init -l app
          fi
          west update --fetch-opt=--filter=tree:0
          west zephyr-export
      - name: Test ${{ matrix.test }} (verbose)
        run: |
          set -euxo pipefail
          cd "$GITHUB_WORKSPACE/app"
          # Use proper ZMK test invocation pattern
          if [ -f "tests/${{ matrix.test }}/testcase.yaml" ]; then
            echo "Running ZMK test for ${{ matrix.test }}"
            west test tests/${{ matrix.test }}
            # Emit DTS tail for diagnostics if build exists
            if [ -f "../build/zephyr/zephyr.dts" ]; then
              echo "===== DTS diagnostics for ${{ matrix.test }} ====="
              tail -n 50 ../build/zephyr/zephyr.dts || true
            fi
          else
            echo "::warning::Skipping ${{ matrix.test }} - no testcase.yaml found"
            echo "Available files in tests/${{ matrix.test }}:"
            ls -la "tests/${{ matrix.test }}/" || true
          fi
      - name: Archive artifacts
        if: ${{ always() && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.test }}-log-files"
          path: app/build/**/*.log
        continue-on-error: true
